deployment:
  stage: deploy
  environment:
    name: aws_lightsail
  before_script:
    - 'which ssh-agent || ( yum update -y && yum install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy to dev server"
    - ssh-add <(echo "$PRIVATE_KEY" | base64 -d)
    # - rm -rf .git
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-204-2-79.compute-1.amazonaws.com "cd /var/urban; docker-compose down; git pull origin master; docker-compose up --build -d;exit"
  only:
    - master


