# Generated by Django 3.1.7 on 2021-04-27 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('chef_street_address', places.fields.PlacesField(blank=True, max_length=255)),
                ('chef_flat_number', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=500)),
                ('postcode', models.CharField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='chef_logo/')),
                ('stripe_user_id', models.CharField(blank=True, max_length=255)),
                ('stripe_access_token', models.CharField(blank=True, max_length=255)),
                ('authorized_to_work_in_the_UK', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('level_2_food_hygiene_certificate', models.FileField(blank=True, null=True, upload_to='chef_certificate/')),
                ('disabled_by_admin', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('customer_street_address', models.CharField(max_length=500)),
                ('customer_flat_number', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='meal_images/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('portion_size', models.CharField(blank=True, help_text='12 pieces or 12 oz. container or others', max_length=255)),
                ('food_type', models.CharField(choices=[('Appentizer', 'Appentizer'), ('Main', 'Main'), ('Side', 'Side'), ('Dessert', 'Dessert')], default=0, max_length=255)),
                ('allergen', multiselectfield.db.fields.MultiSelectField(choices=[('Celery', 'Celery'), ('Gluten', 'Gluten'), ('Crustaceans', 'Crustaceans'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Lupin', 'Lupin'), ('Milk', 'Milk'), ('Molluscs', 'Molluscs'), ('Mustard', 'Mustard'), ('Peanuts', 'Peanuts'), ('Sesame', 'Sesame'), ('Soybeans', 'Soybeans'), ('Sulphur dioxide', 'Sulphur dioxide'), ('Sulphites', 'Sulphites'), ('Nuts', 'Nuts')], default=0, max_length=118)),
                ('cuisine', models.CharField(choices=[('British', 'British'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Pakistani', 'Pakistani'), ('Middle East', 'Middle East'), ('Nepalese', 'Nepalese'), ('Mexican', 'Mexican'), ('Korean', 'Korean'), ('African', 'African'), ('Mediterranean', 'Mediterranean'), ('Caribbean', 'Caribbean'), ('French', 'French'), ('Latin American', 'Latin American'), ('Spanish', 'Spanish'), ('South East Asian', 'South East Asian'), ('European', 'European')], default=0, max_length=255)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=200)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbanshef.chef')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_street_address', models.CharField(max_length=500)),
                ('customer_flat_number', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_instructions', models.CharField(blank=True, max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbanshef.chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbanshef.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urbanshef.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_chef', to='urbanshef.chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_customer', to='urbanshef.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_order', to='urbanshef.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_instructions', models.CharField(blank=True, max_length=500)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbanshef.meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='urbanshef.order')),
            ],
        ),
    ]
