# Generated by Django 3.1.7 on 2021-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='tax',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
