# Generated by Django 3.1.7 on 2021-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0002_auto_20210510_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='agree_terms_and_condition',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
