# Generated by Django 3.1.7 on 2021-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0003_chef_agree_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='cuisine',
            field=models.CharField(choices=[('British', 'British'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Pakistani', 'Pakistani'), ('Middle East', 'Middle East'), ('Nepalese', 'Nepalese'), ('Mexican', 'Mexican'), ('Korean', 'Korean'), ('African', 'African'), ('Mediterranean', 'Mediterranean'), ('Caribbean', 'Caribbean'), ('French', 'French'), ('Latin American', 'Latin American'), ('Spanish', 'Spanish'), ('South East Asian', 'South East Asian'), ('European', 'European')], default=0, max_length=255),
        ),
    ]
