# Generated by Django 3.1.7 on 2021-07-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0009_auto_20210613_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_as_self_employed', models.BooleanField(verbose_name='Register as self employed')),
                ('hygiene_certificate', models.BooleanField(verbose_name='Complete Level 2 Food Hygiene Certificate')),
                ('reg_kitchen_with_council', models.BooleanField(verbose_name='Register kitchen with local council')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_chef', to='urbanshef.chef')),
            ],
        ),
    ]
