# Generated by Django 3.1.7 on 2021-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0011_chef_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_flat_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='stipe_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
