# Generated by Django 3.1.7 on 2021-07-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0012_auto_20210721_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stipe_id',
            new_name='stripe_id',
        ),
    ]
