# Generated by Django 3.1.7 on 2021-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0014_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_flat_number',
            field=models.CharField(default='12', max_length=500),
            preserve_default=False,
        ),
    ]
