# Generated by Django 3.1.7 on 2021-07-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0015_customer_customer_flat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
