# Generated by Django 3.1.7 on 2021-09-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0016_remove_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='level_2_food_hygiene_certificate',
        ),
        migrations.DeleteModel(
            name='CheckList',
        ),
    ]
