# Generated by Django 3.1.7 on 2021-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanshef', '0017_auto_20210927_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='level_2_food_hygiene_certificate',
            field=models.FileField(blank=True, null=True, upload_to='chef_certificate/'),
        ),
    ]
